import type { components } from '@/lib/api/schema';
import type { BracketRound } from './Bracket';

export const bracketFixture: BracketRound[] = [
  {
    round: 1,
    matches: [
      {
        matchNo: 1,
        top: 'E1',
        bottom: 'E2',
        topEntry: {
          entryId: 'E1',
          displayName: 'สมชาย / วิภา',
          teamNames: ['สิงห์ แบดมินตัน'],
        },
        bottomEntry: {
          entryId: 'E2',
          displayName: 'อนันต์ / มาลี',
          teamNames: ['เชียงใหม่ แบด'],
        },
        winner: 'E1',
        status: 'confirmed',
      },
      {
        matchNo: 2,
        top: 'E3',
        bottom: null,
        topEntry: {
          entryId: 'E3',
          displayName: 'กิตติ / สุชาติ',
          teamNames: ['บีจี สปอร์ต'],
        },
        bottomEntry: null,
        winner: 'E3',
        status: 'bye',
      },
      {
        matchNo: 3,
        top: 'E4',
        bottom: 'E5',
        topEntry: {
          entryId: 'E4',
          displayName: 'ธีรเดช / นารี',
          teamNames: ['ภูเก็ต บียอนด์'],
        },
        bottomEntry: {
          entryId: 'E5',
          displayName: 'ปรีชา / ดวงใจ',
          teamNames: ['รัชดา อารีน่า'],
        },
        winner: 'E4',
        status: 'confirmed',
      },
      {
        matchNo: 4,
        top: 'E6',
        bottom: 'E7',
        topEntry: {
          entryId: 'E6',
          displayName: 'วรพจน์ / สุดา',
          teamNames: ['เมืองทอง คลับ'],
        },
        bottomEntry: {
          entryId: 'E7',
          displayName: 'ชัชชัย / กานดา',
          teamNames: ['เอสซีจี แบด'],
        },
        winner: 'E6',
        status: 'confirmed',
      },
    ],
  },
  {
    round: 2,
    matches: [
      {
        matchNo: 5,
        top: 'E1',
        bottom: 'E3',
        topEntry: {
          entryId: 'E1',
          displayName: 'สมชาย / วิภา',
          teamNames: ['สิงห์ แบดมินตัน'],
        },
        bottomEntry: {
          entryId: 'E3',
          displayName: 'กิตติ / สุชาติ',
          teamNames: ['บีจี สปอร์ต'],
        },
        winner: 'E1',
        status: 'reported',
      },
      {
        matchNo: 6,
        top: 'E4',
        bottom: 'E6',
        topEntry: {
          entryId: 'E4',
          displayName: 'ธีรเดช / นารี',
          teamNames: ['ภูเก็ต บียอนด์'],
        },
        bottomEntry: {
          entryId: 'E6',
          displayName: 'วรพจน์ / สุดา',
          teamNames: ['เมืองทอง คลับ'],
        },
        winner: null,
        status: 'scheduled',
      },
    ],
  },
  {
    round: 3,
    matches: [
      {
        matchNo: 7,
        top: null,
        bottom: null,
        topEntry: null,
        bottomEntry: null,
        winner: null,
        status: 'scheduled',
      },
    ],
  },
];

export const sampleBracketRounds = bracketFixture;

export type GroupStanding = components['schemas']['GroupStanding'];

export const standingsFixture: GroupStanding[] = [
  // Group A (group-a)
  {
    groupId: 'group-a',
    entryId: 'E1',
    rank: 1,
    played: 3,
    won: 3,
    drawn: 0,
    lost: 0,
    pointsFor: 63,
    pointsAgainst: 39,
    diff: 24,
    points: 9,
    qualification: 'qualified',
    confirmed: true,
    entry: {
      entryId: 'E1',
      displayName: 'สมชาย / วิภา',
      teamNames: ['สิงห์ แบดมินตัน'],
    },
  },
  {
    groupId: 'group-a',
    entryId: 'E2',
    rank: 2,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    pointsFor: 58,
    pointsAgainst: 52,
    diff: 6,
    points: 6,
    qualification: 'qualified',
    confirmed: true,
    entry: {
      entryId: 'E2',
      displayName: 'อนันต์ / มาลี',
      teamNames: ['เชียงใหม่ แบด'],
    },
  },
  {
    groupId: 'group-a',
    entryId: 'E3',
    rank: 3,
    played: 3,
    won: 1,
    drawn: 0,
    lost: 2,
    pointsFor: 45,
    pointsAgainst: 54,
    diff: -9,
    points: 3,
    qualification: 'best_third_contender',
    confirmed: false, // Provisional row
    entry: {
      entryId: 'E3',
      displayName: 'กิตติ / สุชาติ',
      teamNames: ['บีจี สปอร์ต'],
    },
  },
  {
    groupId: 'group-a',
    entryId: 'E4',
    rank: 4,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    pointsFor: 36,
    pointsAgainst: 57,
    diff: -21,
    points: 0,
    qualification: 'out',
    confirmed: true,
    entry: {
      entryId: 'E4',
      displayName: 'ธีรเดช / นารี',
      teamNames: ['ภูเก็ต บียอนด์'],
    },
  },

  // Group B (group-b)
  {
    groupId: 'group-b',
    entryId: 'E5',
    rank: 1,
    played: 3,
    won: 3,
    drawn: 0,
    lost: 0,
    pointsFor: 63,
    pointsAgainst: 43,
    diff: 20,
    points: 9,
    qualification: 'qualified',
    confirmed: true,
    entry: {
      entryId: 'E5',
      displayName: 'ปรีชา / ดวงใจ',
      teamNames: ['รัชดา อารีน่า'],
    },
  },
  {
    groupId: 'group-b',
    entryId: 'E6',
    rank: 2,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    pointsFor: 56,
    pointsAgainst: 48,
    diff: 8,
    points: 6,
    qualification: 'qualified',
    confirmed: true,
    entry: {
      entryId: 'E6',
      displayName: 'วรพจน์ / สุดา',
      teamNames: ['เมืองทอง คลับ'],
    },
  },
  {
    groupId: 'group-b',
    entryId: 'E7',
    rank: 3,
    played: 3,
    won: 1,
    drawn: 0,
    lost: 2,
    pointsFor: 47,
    pointsAgainst: 55,
    diff: -8,
    points: 3,
    qualification: 'best_third',
    confirmed: true,
    entry: {
      entryId: 'E7',
      displayName: 'ชัชชัย / กานดา',
      teamNames: ['เอสซีจี แบด'],
    },
  },
  {
    groupId: 'group-b',
    entryId: 'E8',
    rank: 4,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    pointsFor: 35,
    pointsAgainst: 55,
    diff: -20,
    points: 0,
    qualification: 'out',
    confirmed: true,
    entry: {
      entryId: 'E8',
      displayName: 'สิทธิชัย / พิมพา',
      teamNames: ['ธนบุรี แบด'],
    },
  },
];
