/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (no DB access) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Member account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterInput"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in; sets auth cookies */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token (reuse detection revokes the family) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description rotated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke session and clear cookies */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, roles, permissions, current approved grade */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a user's roles */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        roles: components["schemas"]["Role"][];
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSummary"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams/clubs */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamPage"];
                    };
                };
            };
        };
        put?: never;
        /** Create a team */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        shortName?: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a user to a team from a date (memberships are dated; draw uses membership on draw date) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        userId: string;
                        /** Format: date */
                        validFrom: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assessments (Member sees own; Committee sees all, filter by status) */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: components["schemas"]["AssessmentStatus"];
                    subjectUserId?: string;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentPage"];
                    };
                };
            };
        };
        put?: never;
        /** Member opens an assessment request (status draft) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Assessment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assessment detail incl. latest result (per-reviewer scores only for Committee) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/clips/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a presigned PUT URL for one clip (draft only; max 3 clips, 500 MB, mp4/mov) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        fileName: string;
                        /** @enum {string} */
                        contentType: "video/mp4" | "video/quicktime";
                        sizeBytes: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            clipId: string;
                            /** Format: uri */
                            uploadUrl: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clips/{clipId}/playback-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fresh presigned GET URL for a clip (owner Member, assigned Reviewer, Committee)
         * @description URL host = S3_PUBLIC_ENDPOINT (prod https://files.<domain>, dev http://localhost:9100). TTL 15 min.
         *     Byte-range requests supported (Caddy files block has no gzip). Web re-calls this when a URL expires.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            url: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
                /** @description CLIP_FORBIDDEN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Member submits the request (draft -> submitted); requires >= 1 uploaded clip */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Assessment"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Committee assigns reviewers (conflict-of-interest checked server-side) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reviewerIds: string[];
                        /**
                         * Format: date-time
                         * @description default now + 72h
                         */
                        dueAt?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentDetail"];
                    };
                };
                /** @description REVIEWER_CONFLICT_OF_INTEREST | ASSESSMENT_NOT_ASSIGNABLE */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Committee approves the latest computed result (pending_approval|disputed -> approved) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description optimistic check — must equal the latest version */
                        resultVersion?: number;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentDetail"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Committee sends back for more reviews (-> in_review) with a reason */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReasonInput"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Super-Committee override — writes a new result version with source=override (see grading.md §8) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OverrideInput"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentDetail"];
                    };
                };
                /** @description OVERRIDE_CONFLICT_OF_INTEREST */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full result history (append-only versions) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assessmentId: components["parameters"]["AssessmentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentResult"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/assignments/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My open/finished review assignments */
        get: {
            parameters: {
                query?: {
                    state?: "open" | "submitted" | "expired";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewAssignment"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/assignments/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignment detail with clip view URLs and the rubric (never other reviewers' scores) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assignmentId: components["parameters"]["AssignmentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewAssignmentDetail"];
                    };
                };
            };
        };
        /** Submit the review (once; immutable after submit) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assignmentId: components["parameters"]["AssignmentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewInput"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewAssignment"];
                    };
                };
                /** @description REVIEW_ALREADY_SUBMITTED | ASSIGNMENT_EXPIRED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/assignments/{assignmentId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reviewer declines (conflict, cannot judge clip) — Committee reassigns */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assignmentId: components["parameters"]["AssignmentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReasonInput"];
                };
            };
            responses: {
                /** @description declined */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rubric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active rubric (criteria, weights, anchors) and method version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rubric"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rater-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rater agreement (Cohen weighted kappa per pair, Fleiss kappa for the panel, bias per rater)
         * @description Reviewer receives only their own row and the panel figure.
         */
        get: {
            parameters: {
                query?: {
                    window?: "30d" | "90d" | "365d" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RaterStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tournaments */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TournamentPage"];
                    };
                };
            };
        };
        put?: never;
        /** Create a tournament */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TournamentInput"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tournament"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an event (e.g. men's singles, grade band S-..S+) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tournamentId: components["parameters"]["TournamentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventInput"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries of an event */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entry"][];
                    };
                };
            };
        };
        put?: never;
        /** Enter an event (singles = 1 player, doubles = 2). Grade must fall in the event band. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        playerIds: string[];
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Entry"];
                    };
                };
                /** @description ENTRY_GRADE_OUT_OF_BAND | ENTRIES_CLOSED | NO_APPROVED_GRADE */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entryId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw an entry (after publish -> walkover/replacement per draw.md §7, never a silent redraw) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReasonInput"];
                };
            };
            responses: {
                /** @description withdrawn */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/draws/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a draw preview (status preview; logged with its seed) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description omit to let the server generate one (CSPRNG) */
                        seed?: string;
                        /** @description omit to use the ruleset default */
                        seedCount?: number;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Draw"];
                    };
                };
                /** @description ENTRIES_NOT_CLOSED | DRAW_ALREADY_LOCKED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/draws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All draw versions of an event (previews + published + superseded) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DrawSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws/{drawId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Draw detail (slots, round-1 matches, conflicts, seed, input hash) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drawId: components["parameters"]["DrawId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Draw"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws/{drawId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a preview. Requires acknowledgeConflicts=true when the draw has unavoidable same-team R1 matches. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drawId: components["parameters"]["DrawId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default false */
                        acknowledgeConflicts?: boolean;
                        /** @description required when this supersedes an already-published draw */
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Draw"];
                    };
                };
                /** @description DRAW_INPUT_CHANGED | DRAW_CONFLICTS_NOT_ACKNOWLEDGED | DRAW_ALREADY_LOCKED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws/{drawId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Re-run the solver from the stored seed + input snapshot and compare (reproducibility check) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    drawId: components["parameters"]["DrawId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            identical: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/bracket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public bracket of the published draw */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bracket"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/format": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the event format (before it is locked by the first group/knockout draw) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventFormat"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventFormat"];
                    };
                };
                /** @description FORMAT_LOCKED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/groups/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Group draw preview (Draw kind=group); publish/verify via the existing /draws endpoints */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        seed?: string;
                        /** @description override when the default sizing rule fails */
                        groupCount?: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Draw"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Groups with members and the round-robin schedule */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/groups/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm group-stage results -> snapshot group_standings, unlock knockout generation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupStanding"][];
                    };
                };
                /** @description GROUP_MATCHES_INCOMPLETE */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live group standings (or the confirmed snapshot) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupStanding"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/knockout/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Knockout draw preview seeded from the confirmed standings (Draw kind=knockout) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: components["parameters"]["EventId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        seed?: string;
                    };
                };
            };
            responses: {
                /** @description ok */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Draw"];
                    };
                };
                /** @description GROUP_STAGE_NOT_CONFIRMED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Enter/edit a match result (validated against the stage MatchFormat; audited) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        outcome: "played" | "walkover_a" | "walkover_b";
                        games?: {
                            a: number;
                            b: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Match"];
                    };
                };
                /** @description STAGE_CONFIRMED */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
                /** @description MATCH_SCORE_INVALID */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnvelopeError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Append-only audit trail */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    entityType?: string;
                    entityId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnvelopeError: {
            /** @constant */
            success: false;
            error: {
                /** @example REVIEW_ALREADY_SUBMITTED */
                code: string;
                /** @description Thai */
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        Role: "Admin" | "Committee" | "Reviewer" | "Member";
        RegisterInput: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
        };
        LoginInput: {
            identifier: string;
            password: string;
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            displayName: string;
            roles: components["schemas"]["Role"][];
            /** Format: uuid */
            teamId?: string | null;
        };
        Me: components["schemas"]["UserSummary"] & {
            /** Format: email */
            email?: string;
            permissions?: string[];
            currentGrade?: components["schemas"]["GradeView"] | null;
        };
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            shortName?: string;
        };
        TeamPage: {
            items: components["schemas"]["Team"][];
            nextCursor?: string | null;
        };
        /**
         * @description 15-rung ladder, index 0..14, ASCII hyphen
         * @enum {string}
         */
        GradeKey: "RK1" | "RK2" | "RK3" | "BG1" | "BG2" | "BG3" | "S-" | "S" | "S+" | "N-" | "N" | "N+" | "P-" | "P" | "P+";
        /** @enum {string} */
        Tier: "Rookie" | "Beginner" | "Standard" | "Neutral" | "Professional";
        /**
         * @description The assessment result shape every client renders. score is continuous in ladder units [0, 15);
         *     interval is half-open [score - margin, score + margin): lower = grade key of floor(score - margin),
         *     upper = grade key of ceil(score + margin) - 1, both clamped to 0..14 (grading.md appendix B.4);
         *     center = grade key of floor(score). label derives from lower/upper/kind.
         */
        GradeView: {
            /** @example 7.4 */
            score: number;
            /** @example 0.6 */
            margin?: number;
            lower: components["schemas"]["GradeKey"];
            upper: components["schemas"]["GradeKey"];
            center: components["schemas"]["GradeKey"];
            tier?: components["schemas"]["Tier"];
            /** @enum {string} */
            kind: "exact" | "straddle" | "wide";
            /**
             * @description exact "S" | straddle "S/S+" | wide "S-–N" (en dash)
             * @example S/S+
             */
            label: string;
        };
        /** @enum {string} */
        AssessmentStatus: "draft" | "submitted" | "in_review" | "needs_reviewers" | "disputed" | "pending_approval" | "approved" | "overridden" | "rejected" | "withdrawn";
        Assessment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            subjectUserId: string;
            status: components["schemas"]["AssessmentStatus"];
            reviewsSubmitted?: number;
            reviewsRequired?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AssessmentPage: {
            items: components["schemas"]["Assessment"][];
            nextCursor?: string | null;
        };
        AssessmentResult: {
            version: number;
            /** @enum {string} */
            source: "computed" | "override";
            /**
             * @description approval state of this result row
             * @enum {string}
             */
            status?: "pending" | "approved" | "superseded";
            grade: components["schemas"]["GradeView"];
            /** @description valid reviews used after exclusion */
            nRaters: number;
            /** @description reviews excluded as outliers */
            nExcluded: number;
            /** @description max - min of used rater scores (ladder units) */
            spread?: number;
            flags?: ("OUTLIER_EXCLUDED" | "HIGH_DISAGREEMENT" | "LOW_RATER_COUNT" | "OVERRIDE")[];
            /** @example grading-v1 */
            methodVersion: string;
            /** @description override only */
            reason?: string;
            /** Format: date-time */
            computedAt: string;
            /**
             * Format: uuid
             * @description null for computed
             */
            computedBy?: string | null;
        };
        /** @description Committee-only view of one reviewer's contribution */
        ReviewerScoreRow: {
            /** Format: uuid */
            reviewerId?: string;
            reviewerName?: string;
            overall?: number;
            excluded?: boolean;
            robustZ?: number | null;
            criteria?: components["schemas"]["CriterionScore"][];
        };
        AssessmentDetail: components["schemas"]["Assessment"] & {
            clips?: components["schemas"]["Clip"][];
            latestResult?: components["schemas"]["AssessmentResult"] | null;
            /** @description Committee only */
            reviewerRows?: components["schemas"]["ReviewerScoreRow"][];
        };
        Clip: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            status?: "pending_upload" | "uploaded" | "rejected";
            /**
             * Format: uri
             * @description presigned GET
             */
            viewUrl?: string;
            durationSec?: number;
        };
        Rubric: {
            methodVersion: string;
            criteria: {
                /** @example footwork */
                key: string;
                nameTh: string;
                weight: number;
                /** @description tier -> description */
                anchorsTh?: {
                    [key: string]: string;
                };
            }[];
        };
        CriterionScore: {
            criterion: string;
            /** @description null = cannot assess from clip */
            gradeKey?: components["schemas"]["GradeKey"] | null;
        };
        ReviewInput: {
            scores: components["schemas"]["CriterionScore"][];
            comment?: string;
        };
        ReviewAssignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assessmentId: string;
            /** @enum {string} */
            state: "open" | "submitted" | "expired" | "declined";
            /** Format: date-time */
            dueAt: string;
            /** Format: date-time */
            submittedAt?: string | null;
        };
        ReviewAssignmentDetail: components["schemas"]["ReviewAssignment"] & {
            clips?: components["schemas"]["Clip"][];
            rubric?: components["schemas"]["Rubric"];
            myScores?: components["schemas"]["CriterionScore"][];
        };
        AgreementValue: {
            /** @description null when below minimum shared subjects */
            kappa?: number | null;
            /** @description subjects used */
            n?: number;
            /** @enum {string} */
            band?: "poor" | "fair" | "moderate" | "substantial" | "almost_perfect" | "insufficient";
        };
        RaterStats: {
            window?: string;
            methodVersion?: string;
            panel?: {
                fleissKappaTier?: components["schemas"]["AgreementValue"];
            };
            raters?: {
                /** Format: uuid */
                reviewerId?: string;
                reviews?: number;
                /** @description mean(rater - leave-one-out consensus) */
                bias?: number;
                kappaVsConsensus?: components["schemas"]["AgreementValue"];
                outlierRate?: number;
                flagged?: boolean;
            }[];
            pairs?: {
                /** Format: uuid */
                a?: string;
                /** Format: uuid */
                b?: string;
                cohenKappaQuadratic?: components["schemas"]["AgreementValue"];
            }[];
        };
        TournamentInput: {
            name: string;
            venue?: string;
            /** Format: date */
            startsOn: string;
            /** Format: date-time */
            entriesCloseAt: string;
        };
        Tournament: components["schemas"]["TournamentInput"] & {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "draft" | "open" | "closed" | "running" | "finished";
        };
        TournamentPage: {
            items: components["schemas"]["Tournament"][];
            nextCursor?: string | null;
        };
        EventInput: {
            /** @enum {string} */
            discipline: "MS" | "WS" | "MD" | "WD" | "XD";
            gradeMin: components["schemas"]["GradeKey"];
            gradeMax: components["schemas"]["GradeKey"];
            maxEntries?: number;
        };
        Event: components["schemas"]["EventInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tournamentId: string;
        };
        Entry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventId: string;
            /** @enum {string} */
            status: "active" | "withdrawn";
            players: {
                /** Format: uuid */
                userId?: string;
                displayName?: string;
                /** Format: uuid */
                teamId?: string | null;
                grade?: components["schemas"]["GradeView"];
            }[];
            /** @description singles = player score; doubles = mean of both (draw.md §3) */
            seedScore?: number;
        };
        DrawSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventId: string;
            version: number;
            /** @enum {string} */
            status: "preview" | "published" | "superseded" | "locked";
            sameTeamR1Count?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            createdBy?: string;
        };
        Draw: components["schemas"]["DrawSummary"] & {
            seed?: string;
            inputHash?: string;
            /**
             * @description group = bl-17 group draw
             * @default knockout
             * @enum {string}
             */
            kind: "knockout" | "group";
            /** @example draw-v1 */
            rulesetVersion?: string;
            /** @description bracket size (power of two) */
            size?: number;
            slots?: {
                /** @description 1..size */
                position?: number;
                /**
                 * Format: uuid
                 * @description null = bye
                 */
                entryId?: string | null;
                seedNo?: number | null;
            }[];
            /** @description unavoidable same-team round-1 matches (empty in the normal case) */
            conflicts?: {
                matchNo?: number;
                /** Format: uuid */
                teamId?: string;
            }[];
            minimumPossibleConflicts?: number;
        };
        Bracket: {
            /** Format: uuid */
            eventId?: string;
            drawVersion?: number;
            rounds?: {
                round?: number;
                matches?: {
                    matchNo?: number;
                    /**
                     * Format: uuid
                     * @description entryId
                     */
                    top?: string | null;
                    /** Format: uuid */
                    bottom?: string | null;
                    /** Format: uuid */
                    winner?: string | null;
                    /** @enum {string} */
                    status?: "scheduled" | "bye" | "walkover" | "finished";
                }[];
            }[];
        };
        MatchFormat: {
            /** @enum {string} */
            preset?: "group_2x15" | "single_30" | "bo3_21" | "single_21" | "custom";
            /** @enum {string} */
            mode: "fixed_games" | "best_of";
            games: number;
            pointsPerGame: number;
            deuce: boolean;
            cap?: number | null;
            /** @default false */
            drawAllowed: boolean;
        };
        EventFormat: {
            /** @enum {string} */
            type: "knockout" | "groups_knockout";
            /** @default 4 */
            groupSize: number;
            /** @default 2 */
            advancePerGroup: number;
            /** @default 0 */
            bestThirds: number;
            groupMatchFormat?: components["schemas"]["MatchFormat"];
            knockoutMatchFormat?: components["schemas"]["MatchFormat"];
            points?: {
                /** @default 3 */
                win: number;
                /** @default 1 */
                draw: number;
                /** @default 0 */
                loss: number;
            };
            tiebreakers?: ("points" | "point_diff" | "head_to_head" | "points_for" | "game_diff" | "lot")[];
            /** @default true */
            thirdPlacePlayoff: boolean;
            /** Format: date-time */
            readonly lockedAt?: string | null;
        };
        Match: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            stage?: "group" | "knockout" | "third_place";
            /** Format: uuid */
            groupId?: string | null;
            round?: number;
            /**
             * Format: uuid
             * @description entryId
             */
            a?: string | null;
            /** Format: uuid */
            b?: string | null;
            games?: {
                a?: number;
                b?: number;
            }[];
            /** @enum {string|null} */
            result?: "a_win" | "b_win" | "draw" | "walkover_a" | "walkover_b" | "void" | null;
            /** @enum {string} */
            status?: "scheduled" | "bye" | "walkover" | "finished" | "void";
        };
        Group: {
            /** Format: uuid */
            id?: string;
            /** @example A */
            label?: string;
            members?: {
                /** Format: uuid */
                entryId?: string;
                seedInGroup?: number;
                pot?: number;
            }[];
            matches?: components["schemas"]["Match"][];
        };
        GroupStanding: {
            /** Format: uuid */
            groupId?: string;
            /** Format: uuid */
            entryId?: string;
            rank?: number;
            played?: number;
            won?: number;
            drawn?: number;
            lost?: number;
            points?: number;
            pointsFor?: number;
            pointsAgainst?: number;
            diff?: number;
            tiebreakNote?: string | null;
            /** @enum {string} */
            qualification?: "qualified" | "best_third" | "best_third_contender" | "out";
            /** @description true when served from the confirmed snapshot */
            confirmed?: boolean;
        };
        AuditPage: {
            items?: {
                /** Format: uuid */
                id?: string;
                /** Format: uuid */
                actorId?: string | null;
                /** @example assessment.override */
                action?: string;
                entityType?: string;
                entityId?: string;
                before?: Record<string, never>;
                after?: Record<string, never>;
                reason?: string | null;
                /** Format: date-time */
                createdAt?: string;
            }[];
            nextCursor?: string | null;
        };
        OverrideInput: {
            centerKey: components["schemas"]["GradeKey"];
            reason: string;
        };
        ReasonInput: {
            reason: string;
        };
    };
    responses: {
        /** @description UNAUTHENTICATED */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeError"];
            };
        };
        /** @description NOT_FOUND */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeError"];
            };
        };
        /** @description state conflict (code says which) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeError"];
            };
        };
        /** @description VALIDATION_FAILED */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EnvelopeError"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        UserId: string;
        TeamId: string;
        AssessmentId: string;
        AssignmentId: string;
        TournamentId: string;
        EventId: string;
        DrawId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
